import type { Empleado } from '@/types'

export const EMPLEADOS: Empleado[] = [
  {
    id: '1',
    nombre: 'María',
    apellido: 'González Pérez',
    cedula: '00112345678',
    cargo: 'Contadora General',
    departamento: 'Contabilidad',
    fechaIngreso: '2021-03-15',
    salarioBase: 55_000,
    tipoContrato: 'fijo',
    activo: true,
    email: 'mgonzalez@empresa.com',
    telefono: '809-555-0101',
    banco: 'Banco Popular',
    numeroCuenta: '200-12345-6',
    categoriaRiesgo: 'I',
  },
  {
    id: '2',
    nombre: 'Carlos',
    apellido: 'Rodríguez Méndez',
    cedula: '00298765431',
    cargo: 'Gerente de Ventas',
    departamento: 'Ventas',
    fechaIngreso: '2019-07-01',
    salarioBase: 88_000,
    tipoContrato: 'fijo',
    activo: true,
    email: 'crodriguez@empresa.com',
    telefono: '829-555-0202',
    banco: 'BanReservas',
    numeroCuenta: '180-98765-4',
    categoriaRiesgo: 'I',
  },
  {
    id: '3',
    nombre: 'Ana',
    apellido: 'Martínez Santos',
    cedula: '00354321987',
    cargo: 'Asistente Administrativa',
    departamento: 'Administración',
    fechaIngreso: '2023-01-10',
    salarioBase: 28_500,
    tipoContrato: 'fijo',
    activo: true,
    email: 'amartinez@empresa.com',
    telefono: '849-555-0303',
    banco: 'BHD León',
    numeroCuenta: '310-11223-3',
    categoriaRiesgo: 'I',
  },
  {
    id: '4',
    nombre: 'José',
    apellido: 'Hernández Cruz',
    cedula: '00476543215',
    cargo: 'Técnico de IT',
    departamento: 'Tecnología',
    fechaIngreso: '2022-09-20',
    salarioBase: 43_000,
    tipoContrato: 'fijo',
    activo: true,
    email: 'jhernandez@empresa.com',
    telefono: '809-555-0404',
    banco: 'Scotiabank',
    numeroCuenta: '490-55667-7',
    categoriaRiesgo: 'I',
  },
  {
    id: '5',
    nombre: 'Patricia',
    apellido: 'Núñez Jiménez',
    cedula: '00523456789',
    cargo: 'Coordinadora de RRHH',
    departamento: 'Recursos Humanos',
    fechaIngreso: '2020-11-05',
    salarioBase: 49_500,
    tipoContrato: 'fijo',
    activo: true,
    email: 'pnunez@empresa.com',
    telefono: '829-555-0505',
    banco: 'BanReservas',
    numeroCuenta: '180-77889-0',
    categoriaRiesgo: 'I',
  },
  {
    id: '6',
    nombre: 'Roberto',
    apellido: 'Díaz Vargas',
    cedula: '00687654322',
    cargo: 'Auxiliar de Almacén',
    departamento: 'Operaciones',
    fechaIngreso: '2024-02-01',
    salarioBase: 21_500,
    tipoContrato: 'temporal',
    activo: true,
    email: 'rdiaz@empresa.com',
    telefono: '849-555-0606',
    banco: 'Banco Popular',
    numeroCuenta: '200-44556-1',
    categoriaRiesgo: 'II',
  },
  {
    id: '7',
    nombre: 'Luisa',
    apellido: 'Reyes Castillo',
    cedula: '00734567890',
    cargo: 'Ejecutiva de Cuentas',
    departamento: 'Ventas',
    fechaIngreso: '2022-04-18',
    salarioBase: 36_000,
    tipoContrato: 'fijo',
    activo: true,
    email: 'lreyes@empresa.com',
    telefono: '809-555-0707',
    banco: 'BHD León',
    numeroCuenta: '310-99001-5',
    categoriaRiesgo: 'I',
  },
  {
    id: '8',
    nombre: 'Miguel',
    apellido: 'Torres Pimentel',
    cedula: '00845678901',
    cargo: 'Mensajero / Conductor',
    departamento: 'Operaciones',
    fechaIngreso: '2025-08-12',
    salarioBase: 21_000,
    tipoContrato: 'temporal',
    activo: false,
    email: 'mtorres@empresa.com',
    telefono: '849-555-0808',
    banco: 'BanReservas',
    numeroCuenta: '180-33445-8',
    categoriaRiesgo: 'II',
  },
]

export const EMPLEADOS_ACTIVOS = EMPLEADOS.filter(e => e.activo)

export const DEPARTAMENTOS = [...new Set(EMPLEADOS.map(e => e.departamento))]
